// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NZE_D2pnHwfAWJ8Hq9ijyRm1udKISAk',
    appId: '1:657605025288:web:dba83482cc695757547bbd',
    messagingSenderId: '657605025288',
    projectId: 'tmsproject-491ab',
    authDomain: 'tmsproject-491ab.firebaseapp.com',
    storageBucket: 'tmsproject-491ab.firebasestorage.app',
    measurementId: 'G-8FQ4J0JJFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByiThOAbRK9KJXSOLK0MdQFiMHZ6ZUVRs',
    appId: '1:657605025288:android:b3507f05936e3cdf547bbd',
    messagingSenderId: '657605025288',
    projectId: 'tmsproject-491ab',
    storageBucket: 'tmsproject-491ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0n3KHRWH2UHWE6rqfGZBLoCXd-L7ycI',
    appId: '1:657605025288:ios:3e04d96b530d7640547bbd',
    messagingSenderId: '657605025288',
    projectId: 'tmsproject-491ab',
    storageBucket: 'tmsproject-491ab.firebasestorage.app',
    iosBundleId: 'com.example.it14TmsFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN0n3KHRWH2UHWE6rqfGZBLoCXd-L7ycI',
    appId: '1:657605025288:ios:3e04d96b530d7640547bbd',
    messagingSenderId: '657605025288',
    projectId: 'tmsproject-491ab',
    storageBucket: 'tmsproject-491ab.firebasestorage.app',
    iosBundleId: 'com.example.it14TmsFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5NZE_D2pnHwfAWJ8Hq9ijyRm1udKISAk',
    appId: '1:657605025288:web:7b7efaff14f1e91d547bbd',
    messagingSenderId: '657605025288',
    projectId: 'tmsproject-491ab',
    authDomain: 'tmsproject-491ab.firebaseapp.com',
    storageBucket: 'tmsproject-491ab.firebasestorage.app',
    measurementId: 'G-4J23P2RC2W',
  );
}
